# Based on https://github.com/galaxy119/EXILED/blob/2.0.0/.github/workflows/main.yml

name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Nuget
      uses: warrenbuckley/Setup-Nuget@v1
    
    - name: Restore Packages
      run: nuget restore BuddyPlugin.sln
      
    - name: Setup MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Download references
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: 'https://www.exiled.host/build_deps/References.zip'
        file-name: 'References.zip'

    - name: Get Exiled DLL URL
      uses: actions/github-script@v2
      id: url
      with:
        result-encoding: string
        github-token: ${{secrets.TOKEN}}
        script: |
          var res = await github.actions.listArtifactsForRepo({
            owner: "galaxy119",
            repo: "EXILED",
          });
          var res2 = await github.actions.downloadArtifact({
            owner: "galaxy119",
            repo: "EXILED",
            artifact_id: res.data.artifacts[0].id,
            archive_format: "zip",
          });
          return res2.url;

    - name: Download Exiled DLLs
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: '${{steps.url.outputs.result}}'
        file-name: 'EXILED.zip'

    - name: Download 7zip
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: 'https://www.exiled.host/7za.exe'
        file-name: '7zip.exe'

    - name: Extract Refs
      run: ./7zip.exe e References.zip -olibs/ -r -y

    - name: Extract Exiled DLLs
      run: ./7zip.exe e EXILED.zip -olibs/ -r -y

    - name: Build
      run: msbuild BuddyPlugin.sln -p:Configuration=release

    - name: Upload Build
      uses: actions/upload-artifact@v2
      with:
        name: Plugin DLL
        path: bin/Release/Buddy.dll
